require 'user.options'
require 'user.keymaps'
require 'user.diff'
require 'user.plugins'
require 'user.impatient'
require 'user.colorscheme'
require 'user.autocommands'
require 'user.cmp'
require 'user.lsp'
require 'user.toggleterm'
require 'user.indentline'
require 'user.treesitter'
require 'user.nvim-tree'
require 'user.telescope'
require 'user.autopairs'
require 'user.project'
require 'user.black'

-- require 'user.gitsigns'
